### ISSUE TITLE
adviser integration tests fail on MOC

### ISSUE THREAD

**Issue by goern** [thoth-station/integration-tests#47] opened 2020-10-03 14:18 UTC
**Describe the bug**
Prow job https://prow.thoth-station.dev/prowjob?prowjob=7fa2eb46-057f-11eb-a5dd-6e8ac1360692 is executing an integration test against MOC deployment. http://argo-ui-thoth-amun-inspection-prod.k-apps.osh.massopen.cloud/workflows that the workflow hangs. It seems to be related to a secret being unmountable, maybe a failed build is also the root cause.

**Comment by harshad16** [comment] 2020-10-06 18:26
isnt this related to amun ?

**Comment by harshad16** [comment] 2020-10-06 19:07
the amun issue is now fixed, was caused by the unfound secrets, updated that.
![integration-test](https://user-images.githubusercontent.com/14028058/95248491-fd8b0480-0834-11eb-917c-f82104e1a76d.png)

working on the adviser run failure.
![moc-adviser](https://user-images.githubusercontent.com/14028058/95248618-3034fd00-0835-11eb-898e-ec2ecb8c95a8.png)

some are caused due to old images, updating them and reverifying.

**Comment by harshad16** [comment] 2020-10-06 19:20
Looking at the logs, of each workflow, the issue occurred are as follows:
The workflow run for this particular execution in the prod cluster had adviser-id: `adviser-d57a1d98`

- advise: following the logs of the pods. it was directed in the log to this justification: https://thoth-station.ninja/j/error_logs
   Along the direction specified will open the issue in adviser.
- investigator-producer: it failed due to an old image having which had issues. 
image version : v0.4.9 , will be updating it to version: > = 0.4.10
- trigger-intergration: due to failure of prior workflow, this didn't get appropriate params.

**Comment by fridex** [comment] 2020-10-07 09:00
What are the logs of adviser? Are there data available to successfully run a resolution?

**Comment by harshad16** [comment] 2020-10-07 10:40
> What are the logs of adviser? Are there data available to successfully run a resolution?

the logs were attached in an issue, created in adviser for tracking.
and no the data is not available need to wait for ingestion to complete.

**Comment by fridex** [comment] 2020-10-07 10:41
> > What are the logs of adviser? Are there data available to successfully run a resolution?
> 
> the logs were attached in an issue, created in adviser for tracking.
> and no the data is not available need to wait for ingestion to complete.

Thanks :+1:

**Comment by goern** [comment] 2020-10-27 20:57
@bissenbay any update on this?

**Comment by harshad16** [comment] 2020-10-28 07:29
> @bissenbay any update on this?

we should run this integration test on stage first, if the adviser run passes, we can update the production with respect to it and then proceed with the adviser run integration test in production.
as of now, in production, we don't have relevant data available for this particular adviser run which is included in the integration test.

**Comment by goern** [comment] 2020-11-04 08:32
@bissenbay any update on this?

**Comment by harshad16** [comment] 2020-11-04 12:20
i guess this is on me, i will update the data in moc production. 
and @bissenbay  then you would be able to verify.

**Comment by fridex** [comment] 2021-02-23 12:20
I will close this one, it looks stalled. The issues discussed are fixed now. Thanks for the report!

**Closed by fridex** 2021-02-23 12:20 UTC
Labels: deployment_name/moc, human_intervention_required, kind/bug
