### ISSUE TITLE
 Run a simple thamos advise for a flask application for raw HTTP connection feature fails

### ISSUE THREAD

**Issue by pacospace** [thoth-station/integration-tests#50] opened 2020-10-05 06:25 UTC
**Describe the bug**
 Run a simple thamos advise for a flask application for raw HTTP connection feature fails

**To Reproduce**
1. Run `THOTH_USER_API_HOST=test.thoth-station.ninja THOTH_MANAGEMENT_API_HOST=management.test.thoth-station.ninja pipenv run behave -i features/thamos_advise.feature`

**Expected behavior**
Integration tests succeeds.

**Screenshots**
```
Feature: Running thamos advise against deployment # features/thamos_advise.feature:1

  Scenario: Run a simple thamos advise for a flask application for raw HTTP connection     # features/thamos_advise.feature:3
    Given deployment is accessible using HTTPS                                             # features/steps/basic.py:31 1.534s
    When thamos advise is run for flask_py36 for recommendation type LATEST asynchronously # features/steps/basic.py:58 2.044s
    Then wait for adviser to finish successfully                                           # features/steps/basic.py:88 0.770s
      Traceback (most recent call last):
        File "/home/fmurdaca/.local/share/virtualenvs/integration-tests-ULlXhRXl/lib/python3.6/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/home/fmurdaca/.local/share/virtualenvs/integration-tests-ULlXhRXl/lib/python3.6/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/basic.py", line 101, in wait_for_adviser_to_finish
          exit_code = response.json()["status"]["exit_code"]
      KeyError: 'exit_code'
      
      Captured logging:
      WARNING:thamos.config:TLS verification turned off, its highly recommended to use a secured connection, see configuration file for configuration options
      INFO:thamos.lib:Successfully submitted advise analysis 'adviser-345f946b' to 'https://test.thoth-station.ninja/api/v1'

    Then I should be able to retrieve adviser results                                      # None
    Then adviser result has pinned down software stack with report                         # None


Failing scenarios:
  features/thamos_advise.feature:3  Run a simple thamos advise for a flask application for raw HTTP connection

0 features passed, 1 failed, 0 skipped
0 scenarios passed, 1 failed, 0 skipped
2 steps passed, 1 failed, 2 skipped, 0 undefined
Took 0m4.348s
```

**Additional context**
See: https://github.com/thoth-station/investigator/issues/301

**Comment by fridex** [comment] 2020-10-05 06:27
> ```
>           exit_code = response.json()["status"]["exit_code"]
>       KeyError: 'exit_code'
> ```

We no longer provide `exit_code` as part of the response

**Comment by fridex** [comment] 2020-10-05 15:48
I'll reopen this until the wait mechanism is in place.

**Comment by goern** [comment] 2020-10-27 20:58
@bissenbay any update on this?

**Comment by goern** [comment] 2020-10-30 14:39
https://github.com/thoth-station/thoth-application/issues/568 might talk about the root cause for this

**Comment by fridex** [comment] 2021-02-23 12:20
The linked issue is fixed now, I'm also able to resolve flask in test/stage/prod environments. Feel free to reopen this one if the issue persists.

**Closed by fridex** 2021-02-23 12:20 UTC
Labels: human_intervention_required, kind/bug
